import { pcPost, COMPANY_ID, corsHeaders } from '../_lib/pc.js'

export default async function handler(req, res) {
  const h = corsHeaders()
  if (req.method === 'OPTIONS') {
    return res.writeHead(204, h).end()
  }
  Object.entries(h).forEach(([k, v]) => res.setHeader(k, v))

  const { messages = [] } = req.body || {}
  const endedAt = new Date().toISOString()
  const dateStr = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  const participants = [...new Set(messages.filter(m => !m.isSystem).map(m => m.from))].join(', ')
  const messageLines = messages.filter(m => !m.isSystem).map(m => `**${m.from}** (${m.time}): ${m.message}`).join('\n')

  const mom = `## Minutes of Meeting — ${dateStr}\n\n**Participants:** ${participants || 'No participants'}\n\n### Discussion\n\n${messageLines || '_No messages recorded._'}\n\n---\n*Auto-generated by ALMO Command Center · ${endedAt}*`

  let postedIssueIdentifier = null
  try {
    const issues = await pcPost(`/api/companies/${COMPANY_ID}/issues?q=council+meeting&limit=3`).catch(() => [])
    const target = issues[0]
    if (target) {
      await fetch(`${process.env.PAPERCLIP_API_URL}/api/issues/${target.id}/comments`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${process.env.PAPERCLIP_API_KEY}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ body: mom }),
      })
      postedIssueIdentifier = target.identifier
    }
  } catch { }

  res.status(200).json({ status: 'ended', mom, postedIssueIdentifier })
}
